version: '3'

services:

  host01:
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - mariadb-net
    environment:
      - MARIADB_ROOT_PASSWORD=secret

  host02:
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - mariadb-net
    environment:
      - MARIADB_ROOT_PASSWORD=secret

  host03:
    image: mariadb:latest
    restart: unless-stopped
    networks:
      - mariadb-net
    environment:
      - MARIADB_ROOT_PASSWORD=secret
  
networks:
  mariadb-net: