version: '3.8'

services:

  host01:
    image: mariadb:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - mariadb-replication
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    volumes:
      - ./host01/config:/etc/mysql/conf.d
      - ./host01/init:/docker-entrypoint-initdb.d

  host02:
    image: mariadb:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      - host01
    networks:
      - mariadb-replication
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    volumes:
      - ./host02/config:/etc/mysql/conf.d
      - ./host02/init:/docker-entrypoint-initdb.d

  host03:
    image: mariadb:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    depends_on:
      - host01
    networks:
      - mariadb-replication
    environment:
      - MARIADB_ROOT_PASSWORD=secret
    volumes:
      - ./host03/config:/etc/mysql/conf.d
      - ./host03/init:/docker-entrypoint-initdb.d

  endpoint:
    image: mariadb/maxscale:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 48M
    depends_on:
      - host03
    networks:
      - mariadb-replication
    ports:
      - 3306:3306
      - 8989:8989
    volumes:
      - ./maxscale/local.cnf:/etc/maxscale.cnf.d/local.cnf

  benchmark01:
    image: ybsc:0.17.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 81M
    build: ./ycsb/
    depends_on:
      - endpoint
    networks:
      - mariadb-replication
    volumes:
      - ./ycsb/db.properties:/app/ycsb-0.17.0/db.properties
      - ./ycsb/replica01.properties:/app/ycsb-0.17.0/replica.properties
      - ./ycsb/results:/results

  benchmark02:
    image: ybsc:0.17.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 81M
    build: ./ycsb/
    depends_on:
      - endpoint
    networks:
      - mariadb-replication
    volumes:
      - ./ycsb/db.properties:/app/ycsb-0.17.0/db.properties
      - ./ycsb/replica02.properties:/app/ycsb-0.17.0/replica.properties
      - ./ycsb/results:/results

  benchmark03:
    image: ybsc:0.17.0
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 81M
    build: ./ycsb/
    depends_on:
      - endpoint
    networks:
      - mariadb-replication
    volumes:
      - ./ycsb/db.properties:/app/ycsb-0.17.0/db.properties
      - ./ycsb/replica03.properties:/app/ycsb-0.17.0/replica.properties
      - ./ycsb/results:/results
  
networks:
  mariadb-replication: